export const savedState: any = {
    turn: 1,
    terminal: false,
    winner: 0,
    blackFigures: [
        // { id: "b_r0", player: -1, index: 0, type: 1, touched: false },
        // { id: "b_k0", player: -1, index: 1, type: 2 },
        // { id: "b_b0", player: -1, index: 2, type: 3 },
        {
            id: "b_k",
            player: -1,
            index: 3,
            type: 5,
            touched: false,
            attacked: new Set(),
        },
        { id: "b_q", player: -1, index: 4, type: 4 },
        // { id: "b_b1", player: -1, index: 5, type: 3 },
        // { id: "b_k1", player: -1, index: 6, type: 2 },
        // { id: "b_r1", player: -1, index: 7, type: 1, touched: false },
        // { id: "b_p0", player: -1, index: 8, type: 0, touched: false },
        // { id: "b_p1", player: -1, index: 9, type: 0, touched: false },
        // { id: "b_p2", player: -1, index: 10, type: 0, touched: false },
        // { id: "b_p3", player: -1, index: 11, type: 0, touched: false },
        // { id: "b_p4", player: -1, index: 12, type: 0, touched: false },
        // { id: "b_p5", player: -1, index: 13, type: 0, touched: false },
        // { id: "b_p6", player: -1, index: 14, type: 0, touched: false },
        // { id: "b_p7", player: -1, index: 15, type: 0, touched: false },
    ],
    whiteFigures: [
        // { id: "w_r0", player: 1, index: 56, type: 1, touched: false },
        // { id: "w_k0", player: 1, index: 57, type: 2 },
        //{ id: "w_b0", player: 1, index: 58, type: 3 },
        {
            id: "w_k",
            player: 1,
            index: 59,
            type: 5,
            touched: false,
            attacked: new Set(),
        },
        { id: "w_q", player: 1, index: 60, type: 4 },
        // { id: "w_b0", player: 1, index: 61, type: 3 },
        // { id: "w_k1", player: 1, index: 62, type: 2 },
        // { id: "w_r1", player: 1, index: 63, type: 1, touched: false },
        // { id: "w_p0", player: 1, index: 48, type: 0, touched: false },
        // { id: "w_p1", player: 1, index: 49, type: 0, touched: false },
        // { id: "w_p2", player: 1, index: 50, type: 0, touched: false },
        // { id: "w_p3", player: 1, index: 51, type: 0, touched: false },
        // { id: "w_p4", player: 1, index: 52, type: 0, touched: false },
        // { id: "w_p5", player: 1, index: 53, type: 0, touched: false },
        // { id: "w_p6", player: 1, index: 54, type: 0, touched: false },
        // { id: "w_p7", player: 1, index: 55, type: 0, touched: false },
    ],
    actionHistory: [],
};
